### PR TITLE
Hotfix: Changed RemoteStatus constructor to `protected`

### LINKED ISSUE #744: Analysis results cause issues when running with synchronized data
## Describe the bug
When running an analysis with synchronized data (tested with SNVPhyl) it causes the analysis results page to hang.  Analysis must be run with all synchronized data.

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Synchronized data from another IRIDA
2. Ran SNVPhyl with that data
3. Tried to view results or view analysis listing page.  Page either threw error or hung.

## Expected behaviour
Show the listing or results page.\

## Additional context

Exception:
```
ERROR org.hibernate.proxy.pojo.bytebuddy.ByteBuddyProxyFactory:96 - HHH000143: Bytecode enhancement failed because no public, protected or package-private default constructor was found for entity: ca.corefacility.bioinformatics.irida.model.remote.RemoteStatus. Private constructors don't work with runtime proxies!
java.lang.NoSuchMethodException: ca.corefacility.bioinformatics.irida.model.remote.RemoteStatus$HibernateProxy$XXXX.<init>()
```

### PR DESCRIPTION
**Pull request by tom114**
## Description of changes
Changed the `RemoteStatus` constructor to `protected` instead of `private`.  Hibernate had some changes with an update that changes the way proxies are created.  Apparently they have issues with `private` default constructors.  This appeared when trying to run an analysis with remote synchronized data.

Note this is a hotfix merge and must be merged into both `master` and `development`.

## Related issue
Fixes #744 

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [x] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
~* [ ] Tests added (or description of how to test) for any new features.~
~* [ ] User documentation updated for UI or technical changes.~

### CODE REVIEW

File: src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/AnnouncementControlPage.java [hunk 1]
```diff
@@ -79,10 +80,11 @@ public void clickCreateNewAnnouncementButton() {
     }
 
     public void gotoMessageDetails(int index) {
-        List<WebElement> messages = driver.findElements(By.cssSelector("td.t-announcement a"));
+        List<WebElement> messages = driver.findElements(By.cssSelector("td.t-announcement p"));
```
Comment (tom114) [inline src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/AnnouncementControlPage.java:83]: This change was pulled in from https://github.com/phac-nml/irida/pull/699 as announcements page tests were failing.

File: src/main/webapp/package.json [hunk 2]
```diff
@@ -99,7 +99,7 @@
     "babel-loader": "^8.1.0",
     "babel-plugin-import": "^1.13.0",
     "bootstrap-sass": "^3.3.7",
-    "chromedriver": "^79.0.0",
+    "chromedriver": "latest",
```
Comment (tom114) [inline src/main/webapp/package.json:102]: Had to update chromedriver in this branch as well so tests would run correctly.
