### PR TITLE
Fixes issue with creating linelist templates

### LINKED ISSUE #369: Can only create one metadata/line list template
## Describe the bug

It looks like I can only create one metadata/line list template. The first template creation is fine:

image

But, when I next go to create a new template, pressing **Save**:

image

Nothing gets saved. The following exception gets thrown in Java:

```
26 Apr 2019 15:15:58,197 ERROR ca.corefacility.bioinformatics.irida.ria.web.errors.ExceptionHandlerController:117 - Could not read document: Can not construct instance of java.lang.Boolean from String value 'agDateColumnFilter': only "true" or "false" recognized
 at [Source: java.io.PushbackInputStream@40aa82fa; line: 1, column: 212] (through reference chain: ca.corefacility.bioinformatics.irida.ria.web.linelist.dto.UIMetadataTemplate["fields"]->java.util.ArrayList[0]->ca.corefacility.bioinformatics.irida.ria.web.components.agGrid.A
gGridColumn["filter"]); nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.lang.Boolean from String value 'agDateColumnFilter': only "true" or "false" recognized
 at [Source: java.io.PushbackInputStream@40aa82fa; line: 1, column: 212] (through reference chain: ca.corefacility.bioinformatics.irida.ria.web.linelist.dto.UIMetadataTemplate["fields"]->java.util.ArrayList[0]->ca.corefacility.bioinformatics.irida.ria.web.components.agGrid.A
gGridColumn["filter"])                                                                                                                   
org.springframework.http.converter.HttpMessageNotReadableException: Could not read document: Can not construct instance of java.lang.Boolean from String value 'agDateColumnFilter': only "true" or "false" recognized
 at [Source: java.io.PushbackInputStream@40aa82fa; line: 1, column: 212] (through reference chain: ca.corefacility.bioinformatics.irida.ria.web.linelist.dto.UIMetadataTemplate["fields"]->java.util.ArrayList[0]->ca.corefacility.bioinformatics.irida.ria.web.components.agGrid.A
gGridColumn["filter"]); nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.lang.Boolean from String value 'agDateColumnFilter': only "true" or "false" recognized
 at [Source: java.io.PushbackInputStream@40aa82fa; line: 1, column: 212] (through reference chain: ca.corefacility.bioinformatics.irida.ria.web.linelist.dto.UIMetadataTemplate["fields"]->java.util.ArrayList[0]->ca.corefacility.bioinformatics.irida.ria.web.components.agGrid.A
gGridColumn["filter"])                                                                                             
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:224)
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:208)
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:197)
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:147)
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:125)
        at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:78)
        at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:162)
...
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.lang.Boolean from String value 'agDateColumnFilter': only "true" or "false" recognized
 at [Source: java.io.PushbackInputStream@40aa82fa; line: 1, column: 212] (through reference chain: ca.corefacility.bioinformatics.irida.ria.web.linelist.dto.UIMetadataTemplate["fields"]->java.util.ArrayList[0]->ca.corefacility.bioinformatics.irida.ria.web.components.agGrid.A
gGridColumn["filter"])                                                                                                                     
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:55)                                                                                         
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:883)                                                    
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseBoolean(StdDeserializer.java:200)
```

## Steps to reproduce the problem
1. In **Line List** page, create a first initial metadata template.
2. Try to create a new template with different columns.
3. The error will occur here and no template will be saved.

## Expected behaviour

I expected to be able to save the new template.

## Additional context

Tested in **Chromium** and **Firefox** in Linux.

### PR DESCRIPTION
**Pull request by joshsadam**
## Description of changes
It appears the issue with saving linelist templates was the way that the filter variable is being parsed.  Changed this to a string for server parsing.  This lead to having to explicitly ignore the filter for the icon column in the table.

## Related issue
Fixes #369 

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [X] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [X] Tests added (or description of how to test) for any new features.
~~* [ ] User documentation updated for UI or technical changes.~~

### CODE REVIEW

**Comment by joshsadam** [comment]
@tom114 any string in the filter is used by ag-grid to indicate the type of filter that needs to be placed on the column.  In this case, since the column is a date column, a date filter is being used (the default date filter provided by ag-grid is `agDateColumnFilter`).

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/agGrid/AgGridColumn.java [hunk 1]
```diff
@@ -166,11 +166,11 @@ public void setHeaderCheckboxSelection(boolean headerCheckboxSelection) {
 		this.headerCheckboxSelection = headerCheckboxSelection;
 	}
 
-	public boolean isFilter() {
+	public String isFilter() {
```
Comment (tom114) [inline src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/agGrid/AgGridColumn.java]: Can you rename this to `getFilter`?  `isFilter` semantics say that's a boolean.

Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/agGrid/AgGridColumn.java]: Fixed in e7241ee69920b5a64b5dcc93be17ee771cb4e513
