### PR TITLE
Fix for samples not rendering on project samples page when config property ngsarchive.linker.available set to false

### LINKED ISSUE #958: Setting the property ngsarchive.linker.available=false causes an error on the project_samples page
## Describe the bug
Setting the property `ngsarchive.linker.available=false` in the file `configuration.properties` causes the page that lists the samples of a project to go in error.  Apparently the file Linker.jsx needs the line `<span id="linker"></span>` in `project_samples.html`.

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Set `ngsarchive.linker.available=false` in the file `configuration.properties`
2. Restart IRIDA
3. Open a project on the page listing its samples, the samples are not listed

## Expected behaviour
The page shows the samples of the project

### PR DESCRIPTION
**Pull request by ksierks**
## Description of changes
Added a conditional check that the html element exists before rendering the Linker component.

## Related issue
Fixes #958

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [x] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] ~Tests added (or description of how to test) for any new features.~
* [ ] ~User documentation updated for UI or technical changes.~

### CODE REVIEW

File: src/main/webapp/resources/js/pages/projects/samples/linker/Linker.jsx [hunk 1]
```diff
@@ -110,4 +110,7 @@ function Linker() {
   );
 }
 
-render(<Linker />, document.querySelector("#linker"));
+let linker_html = document.querySelector("#linker");
```
Comment (joshsadam) [inline src/main/webapp/resources/js/pages/projects/samples/linker/Linker.jsx:113]: Don;t know about using snake case but I will give it to you here :)

**Review by joshsadam — APPROVED** [review]
This looks good
