### PR TITLE
Fix remote oath for remote connections

### LINKED ISSUE #792: Remote API OAuth2 authorization_token flow broken on Chrome across domains
## Describe the bug
When trying to connect to a remote api from a different URL domain in Chrome, you're presented with a URL page even if you're already logged in to the remote API.  The logged-in session is not accessible from Chrome.

## Steps to reproduce the problem
**Note to reproduce this issue you must test with 2 IRIDA installations running on different domains.**

1. Using Chrome browser, go to the remote-api details page and click connect
2. The connection login iframe is displayed with a login even if you're already logged in to the remote site
3. Enter your credentials and click login.  The login page will be re-displayed with no indication of what went wrong.

## Expected behaviour
I expected to be given an OAuth2 authorization page after logging in, and for my remote API connection to be successful.

## Additional context

As of Chrome 80, they've added a security feature to restrict cookies being used in cross-site requests.  IRIDA's remote API connection flow.  In IRIDA since we use an iframe to display the connection page, the new security feature kicks in and fails to send the session ID to the remote IRIDA instance as that's considered a "cross-site" request.  

This will need to be updated somehow to have the login page on a separate window or tab to avoid the "same-site" restriction.  Note this change is expected to come to all browsers in the near future.

Info on cross-site cookies in chromium at https://www.chromium.org/updates/same-site

### PR DESCRIPTION
**Pull request by joshsadam**
## Description of changes
* Remote connection details
  * Complete refactor using Ant Design within the Admin Panel
  * Updated to use the new Oauth through a seperate window
* Create Remote Project
  * Complete refactor using Ant Design
  * Updated to use new Oauth through seperate window
* Remote Project Settings
  * Complete refactor using Ant Design
  * Updated to use new Oauth through seperate window

## Related issue
Fixes #792 

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [X] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [X] Tests added (or description of how to test) for any new features.
* [X] User documentation updated for UI or technical changes.

### CODE REVIEW

File: src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/remoteapi/RemoteAPIDetailsPage.java [hunk 1]
```diff
@@ -56,76 +83,75 @@ public void confirmDelete() {
...
-				}
-			} catch (StaleElementReferenceException e) {
-				logger.debug("Got stale element reference exception when trying to get text on h1, trying again.");
-			}
-		} while (!deleted);
-
-
-		return deleted;
-	}
+//	public boolean checkDeleteSuccess() {
```
Comment (tom114) [inline src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/remoteapi/RemoteAPIDetailsPage.java:120]: Remove commented out code or re-enable if needed please.

File: src/main/webapp/resources/js/pages/admin/components/remote-connections/RemoteApiStatus.jsx [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+      <IconLoading style={{ marginRight: SPACE_XS }} />
+      {i18n("RemoteApi.checking")}
+    </span>
+  ) : (
+    <div>
+      {expiration ? (
+        <Alert
+          className="t-remote-status-connected"
+          message={i18n(
+            "RemoteApi.connected",
```
Comment (tom114) [inline src/main/webapp/resources/js/pages/admin/components/remote-connections/RemoteApiStatus.jsx:77]: Issue with this new expiration message.  It doesn't actually check if the connection is valid before displaying this message.  There could be a case where the token is revoked but it just displays the expires message instead of validating the token.

Steps to reproduce:
1. Create client, remote api, and connect
2. Go to clients and revoke the token
3. Look at remote api pages and it just says "expires whenever" and doesn't actually check if its valid

In this case it should display the "connect" button again so users can get their new token.

**Review by tom114 — CHANGES_REQUESTED** [review]

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/CreateRemoteProjectRequest.java [hunk 3]
```diff
@@ -0,0 +1,35 @@
+package ca.corefacility.bioinformatics.irida.ria.web.ajax;
+
+import ca.corefacility.bioinformatics.irida.model.project.ProjectSyncFrequency;
+
+/**
+ * Used to capture details about creating a new remote project through the UI
+ */
+public class CreateRemoteProjectRequest {
```
Comment (tom114) [inline src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/CreateRemoteProjectRequest.java:8]: Should this go into the `dto` path instead of just in the base `ajax` one?

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/RemoteAPIAjaxController.java [hunk 4]
```diff
@@ -0,0 +1,148 @@
...
+import ca.corefacility.bioinformatics.irida.ria.web.models.tables.TableRequest;
+import ca.corefacility.bioinformatics.irida.ria.web.models.tables.TableResponse;
+import ca.corefacility.bioinformatics.irida.ria.web.rempoteapi.dto.RemoteAPITableModel;
+import ca.corefacility.bioinformatics.irida.ria.web.services.UIRemoteAPIService;
+import ca.corefacility.bioinformatics.irida.service.RemoteAPIService;
+
+/**
+ * Controller for asynchronous requests for remote api functionality.
+ */
+@RestController
```
Comment (tom114) [inline src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/RemoteAPIAjaxController.java:32]: This should not need a `@RestController` mapping.  Just `@Controller` right?

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/RemoteProjectSettingsUpdateRequest.java [hunk 5]
```diff
@@ -0,0 +1,48 @@
+package ca.corefacility.bioinformatics.irida.ria.web.ajax.dto;
+
+import ca.corefacility.bioinformatics.irida.model.project.ProjectSyncFrequency;
+
+/**
+ * Used to handle requests from the UI to update settings for a remote sync'd project.
+ * The field is the attribute to be update, and the value is the value to set to that field.
+ */
+
+public class RemoteProjectSettingsUpdateRequest {
```
Comment (tom114) [inline src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/RemoteProjectSettingsUpdateRequest.java:10]: There's enough of these `dto` classes to make a sub package for the Remote API stuff.  That package is getting messy.

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectSettingsRemoteAjaxController.java [hunk 6]
```diff
@@ -0,0 +1,77 @@
...
+import ca.corefacility.bioinformatics.irida.ria.web.ajax.dto.ajax.AjaxErrorResponse;
+import ca.corefacility.bioinformatics.irida.ria.web.ajax.dto.ajax.AjaxResponse;
+import ca.corefacility.bioinformatics.irida.ria.web.ajax.dto.ajax.AjaxUpdateItemSuccessResponse;
+import ca.corefacility.bioinformatics.irida.ria.web.services.UIRemoteProjectService;
+
+/**
+ * Controller for managing settings for a remotely sync'd project
+ * asynchronously
+ */
+@RestController
```
Comment (tom114) [inline src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectSettingsRemoteAjaxController.java:24]: Again, this should likely be a `@Controller`

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectSettingsRemoteController.java [hunk 7]
```diff
@@ -29,88 +21,16 @@
...
-	private MessageSource messageSource;
 	private ProjectService projectService;
-	private ProjectRemoteService projectRemoteService;
-	private UserService userService;
 	private ProjectControllerUtils projectControllerUtils;
 
 	@Autowired
-	public ProjectSettingsRemoteController(MessageSource messageSource, ProjectService projectService,
-			ProjectRemoteService projectRemoteService, UserService userService,
+	public ProjectSettingsRemoteController(ProjectService projectService,
```
Comment (tom114) [inline src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectSettingsRemoteController.java:28]: Do we need 2 separate classes for this?  It's a combined 3 methods between this class and the Ajax controller.

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIRemoteAPIService.java [hunk 8]
```diff
@@ -0,0 +1,120 @@
...
+import ca.corefacility.bioinformatics.irida.service.ProjectService;
+import ca.corefacility.bioinformatics.irida.service.RemoteAPIService;
+import ca.corefacility.bioinformatics.irida.service.RemoteAPITokenService;
+import ca.corefacility.bioinformatics.irida.service.remote.ProjectRemoteService;
+
+/**
+ * UI Service to handle request for Remote APIs
+ */
+@Component
+public class UIRemoteAPIService {
```
Comment (tom114) [inline src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIRemoteAPIService.java:29]: What's the point of this class?  It's just re-wrapping other service methods.  Every method is only called from one place.  Why not just have the functionality in those places?

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIRemoteProjectService.java [hunk 9]
```diff
@@ -0,0 +1,132 @@
...
+
+@Component
+public class UIRemoteProjectService {
+	private MessageSource messageSource;
+	private ProjectService projectService;
+	private ProjectRemoteService projectRemoteService;
+	private UserService userService;
+
+	@Autowired
+	public UIRemoteProjectService(MessageSource messageSource, ProjectService projectService,
```
Comment (tom114) [inline src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIRemoteProjectService.java:36]: Same deal with this class.  These 2 methods are only used in one place.  Why add an extra class?

File: src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSyncPage.java [hunk 10]
```diff
@@ -38,19 +37,25 @@ public static ProjectSyncPage goTo(WebDriver driver) {
...
-	public void openAdvanced() {
-		advancedToggle.click();
+	public void selectProjectInListing(String name) {
+		WebDriverWait wait = new WebDriverWait(driver, 2);
+		wait.until(ExpectedConditions.elementToBeClickable(projectSelection));
+		projectSelection.findElement(By.className("ant-select-selection-search")).click();
+		driver.switchTo().activeElement().sendKeys(name);
+		driver.switchTo().activeElement().sendKeys(Keys.ENTER);
+//		wait.until(ExpectedConditions.visibilityOfAllElementsLocatedBy(By.className("ant-select-item")));
+//		driver.findElements(By.className("ant-select-item")).get(index).click();
```
Comment (tom114) [inline src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSyncPage.java:58]: Remove commented code

File: src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/oauth/RemoteAPIAjaxControllerTest.java [hunk 11]
```diff
@@ -149,18 +142,4 @@ public void getAjaxAPIListTest() {
 		assertEquals("Should have 1 Remote API", 1, response.getDataSource()
 				.size());
 	}
-
-	@Test
-	public void checkAPIStatusTest() {
```
Comment (tom114) [inline src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/oauth/RemoteAPIAjaxControllerTest.java:154]: Is this test re-written somewhere else?

File: src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/remoteapi/CreateRemoteAPIPageIT.java [hunk 12]
```diff
@@ -1,30 +1,33 @@
...
-import static org.junit.Assert.*;
+import static org.junit.Assert.assertFalse;
+import static org.junit.Assert.assertTrue;
 
 /**
  * IT for the client details page
  *
  */
 @DatabaseSetup("/ca/corefacility/bioinformatics/irida/ria/web/oauth/CreateRemoteApisIT.xml")
+@Ignore
```
Comment (tom114) [inline src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/remoteapi/CreateRemoteAPIPageIT.java:24]: All these tests need re-enabled

**Review by tom114 — CHANGES_REQUESTED** [review]

File: src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/remoteapi/RemoteAPIDetailsPage.java (hunk 1 above)
Comment (joshsadam) [reply src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/remoteapi/RemoteAPIDetailsPage.java]: Removed in e965419

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/RemoteAPIAjaxController.java (hunk 4 above)
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/RemoteAPIAjaxController.java:33]: No this is completely intentional.  "_@RestController_ is a specialized version of the controller. It includes the @controller and @responsebody annotations and as a result, simplifies the controller implementation" from [https://www.baeldung.com/spring-controller-vs-restcontroller](https://www.baeldung.com/spring-controller-vs-restcontroller) This works since this is a purely AJAX controller.

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/RemoteProjectSettingsUpdateRequest.java (hunk 5 above)
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/RemoteProjectSettingsUpdateRequest.java]: Sure, that makes sense. Updated in276dbcfde37eb7f873588b4ee2bb58652775aaf3

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectSettingsRemoteAjaxController.java (hunk 6 above)
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectSettingsRemoteAjaxController.java:24]: Nope, same comment as above

File: src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSyncPage.java (hunk 10 above)
Comment (joshsadam) [reply src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSyncPage.java]: Removed in 4d34497

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectSettingsRemoteController.java (hunk 7 above)
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectSettingsRemoteController.java:28]: @deepsidhu85  and I have been working really hard at keeping all the controllers really lean and only handling what their job is.  A @controller's job is to return a view and that's it, a `@RestController` is to handle an ajax request.  If either of those those actually need some data (which is basically always for the ajax controllers), they can reach out to a specifically designed service.  That way it is easy to know where to go to find/fix a problem.  It keeps the controllers nice and lean and easy to read and way easier to test.

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIRemoteProjectService.java (hunk 9 above)
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIRemoteProjectService.java:36]: Same deal here, please see above response.

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/RemoteAPIAjaxController.java [hunk 13]
```diff
@@ -0,0 +1,149 @@
...
+@RequestMapping("/ajax/remote_api")
+public class RemoteAPIAjaxController {
+    private final RemoteAPIService remoteAPIService;
+    private final UIRemoteAPIService service;
+
+    public static final String INVALID_OAUTH_TOKEN = "invalid_token";
```
Comment (deepsidhu85) [inline src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/RemoteAPIAjaxController.java:39]: Looks like this isn't being used and can be removed

**Review by deepsidhu85 — CHANGES_REQUESTED** [review]

File: src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/remoteapi/CreateRemoteAPIPageIT.java (hunk 12 above)
Comment (joshsadam) [reply src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/remoteapi/CreateRemoteAPIPageIT.java]: Updated in f1c4406

File: src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/oauth/RemoteAPIAjaxControllerTest.java (hunk 11 above)
Comment (joshsadam) [reply src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/oauth/RemoteAPIAjaxControllerTest.java:154]: Yes, they are all in the UIRemoteAPIServiceTest

**Review by deepsidhu85 — APPROVED** [review]

**Review by tom114 — APPROVED** [review]
