### PR TITLE
Antd project samples

### LINKED ISSUE #973: Create New Sample in Project modal not resetting when adding multiple samples
## Describe the bug

When creating a sample in a project, after adding a sample and then attempting to add another sample right away the previously added sample's name is still displayed in the `Create New Sample in Project` modal with the validation icon 

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Created a sample in a project named `Sample1`
2. Clicked the Sample Tools > Add New Sample link
3. The modal was not reset and still had `Sample1` and it's validation icon in the `Sample Name` text box

## Expected behaviour
After doing the above steps I expected the modal to be reset and not have the previously added sample's name prefilled in the `Sample Name` text box

## Additional context
Additional information to help solve the problem.  Test files, screenshots, IRIDA version information can go here.

### PR DESCRIPTION
**Pull request by joshsadam**
## Description of changes

What did you change in this pull request? Provide a description of files changed, user interactions changed, etc. Include how to test your changes.

## Related issue

Fixes #973 

## Checklist

Things for the developer to confirm they've done before the PR should be accepted:

*   [x] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
*   [x] Tests added (or description of how to test) for any new features.
*   [x] User documentation updated for UI or technical changes.

### CODE REVIEW

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/ProjectSamplesAjaxController.java [hunk 1]
```diff
@@ -49,6 +71,126 @@ public ResponseEntity<SampleNameValidationResponse> validateNewSampleName(@Reque
...
+	 * @param locale  current users {@link Locale}
+	 * @return Outcome of the share/move
+	 */
+	@PostMapping("/share")
+	public ResponseEntity<AjaxResponse> shareSamplesWithProject(@RequestBody ShareSamplesRequest request,
+			Locale locale) {
+		try {
+			uiSampleService.shareSamplesWithProject(request, locale);
+			return ResponseEntity.ok(new AjaxSuccessResponse(""));
+		} catch (Exception e) {
```
Comment (ericenns) [inline src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/ProjectSamplesAjaxController.java:192]: Please change this to a specific exception instead of the generic `Exception` as that will capture a lot more and potentially leak sensitive info.

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectAssociatedProjectsAjaxController.java [hunk 2]
```diff
@@ -73,8 +83,7 @@ public ResponseEntity<AjaxResponse> removeAssociatedProject(@RequestParam long p
 			service.removeAssociatedProject(projectId, associatedProjectId, locale);
 			return ResponseEntity.ok(new AjaxSuccessResponse(""));
 		} catch (Exception e) {
```
Comment (ericenns) [inline src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectAssociatedProjectsAjaxController.java:85]: Please change this to a specific exception instead of the generic Exception as that will capture a lot more and potentially leak sensitive info.

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/ProjectSamplesAjaxController.java (hunk 1 above)
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/ProjectSamplesAjaxController.java]: Updated in a54773bb40f123d5cf6ccd4d62fa7f71d39b8b11

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectAssociatedProjectsAjaxController.java [hunk 3]
```diff
@@ -53,8 +64,7 @@ public ResponseEntity<AjaxResponse> addAssociatedProject(@RequestParam long proj
 			service.addAssociatedProject(projectId, associatedProjectId, locale);
 			return ResponseEntity.ok(new AjaxSuccessResponse(""));
 		} catch (Exception e) {
```
[the remark this answers is not in the document]
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectAssociatedProjectsAjaxController.java]: Updated in cb8ac126b830e6be2958a8fb2c65121b9d354d7c

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectAssociatedProjectsAjaxController.java (hunk 2 above)
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectAssociatedProjectsAjaxController.java]: Updated in cb8ac126b830e6be2958a8fb2c65121b9d354d7c

File: src/main/resources/i18n/messages.properties [hunk 4]
```diff
@@ -2782,3 +2773,91 @@ CreateProjectMetadataRestrictions.noSampleMetadata.description=The existing samp
...
+
+# ========================================================================================== #
+# PROJECT SAMPLES PAGE                                                                       #
+# ========================================================================================== #
+MergeModal.title=Merge Sample
+MergeModal.okText=Merge Samples
+MergeModal.cancelText=Cancel
+MergeModal.metadata-warning=Only the metadata from the selected sample will be retained.
+MergeModal.input-primary=Select sample to retain name and metadata from
+MergeModal.error-valid=ust have at least 2 non-locked samples to merge
```
Comment (deepsidhu85) [inline src/main/resources/i18n/messages.properties:2785]: Typo `Must`

**Review by deepsidhu85 — CHANGES_REQUESTED** [review]
Here is my first part of the review (back end only). Looking good just some minor changes for now

File: .gitignore [hunk 5]
```diff
@@ -31,3 +31,11 @@ src/main/webapp/node
 /src/main/webapp/.pnp.*
 
 doc/swagger-ui/open-api.json
+/src/main/webapp/.yarn/sdks/eslint/lib/api.js
```
[the remark this answers is not in the document]
Comment (joshsadam) [reply .gitignore:34]: @ericenns what is going on here.  On line 29 you explicitly allowed the sdks directory.  Should we just ignore it?

File: CHANGELOG.md [hunk 6]
```diff
@@ -24,6 +24,7 @@ Changes
 * [Developer]: Updated nodejs to `v16.15.0` in the `pom.xml` file.
 * [Developer]: Updated redux API within the cart page to use Redux Toolkit.
 * [All]: Added functionality for project managers to restrict metadata fields depending on the Collaborator's metadata role on the project.
+* [UI]: Complete update to the project samples page to use Ant Design.
```
[the remark this answers is not in the document]
Comment (joshsadam) [reply CHANGELOG.md:27]: Updated in ad895c59f66c61ead63c6711dd2d9470f069d5e8

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/dto/samples/SampleIdsRequest.java [hunk 7]
```diff
@@ -0,0 +1,18 @@
+package ca.corefacility.bioinformatics.irida.ria.web.projects.dto.samples;
```
[the remark this answers is not in the document]
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/dto/samples/SampleIdsRequest.java]: Looks like `SampleIdsRequest.java` was actually not being used anywhere so removed it in 05b8537

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectAssociatedProjectsAjaxController.java [hunk 8]
```diff
@@ -38,6 +40,17 @@ public ResponseEntity<List<AssociatedProject>> getAssociatedProjects(@RequestPar
...
 	}
 
+	/**
+	 * Get a list of all projects associated with the current project.
+	 *
+	 * @param projectId project identifier for the currently active project
+	 * @return list of projects
+	 */
+	@GetMapping("/list")
+	public ResponseEntity<List<AssociatedProject>> getAssociatedProjectsForProject(@RequestParam long projectId) {
```
[the remark this answers is not in the document]
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectAssociatedProjectsAjaxController.java:50]: All the `projectIds` in this controller are being asked for as a `long` why do you want me to change it to a `Long`?

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java [hunk 9]
```diff
@@ -184,38 +182,18 @@ public ResponseEntity<AjaxResponse> getFilesForSample(@PathVariable Long id,
 	}
 
 	/**
-	 * Get a list of all {@link Sample} identifiers within a specific project
+	 * Check if a list of sample names exist within a project
 	 *
-	 * @param projectId Identifier for a Project
-	 * @return {@link List} of {@link Sample} identifiers
+	 * @param request Request containing the project id and sample names
```
[the remark this answers is not in the document]
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java:187]: Updated in edd2edced9213b33d4cf4a0c96e1cfa52205d8fa

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java [hunk 10]
```diff
@@ -184,38 +182,18 @@ public ResponseEntity<AjaxResponse> getFilesForSample(@PathVariable Long id,
...
+	 * @return List of valid and invalid sample names
```
[the remark this answers is not in the document]
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java:188]: Updated in 59d962683e5055fe8e3c334043a7a89634332033

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIAssociatedProjectsService.java [hunk 11]
```diff
@@ -85,15 +98,16 @@ public List<AssociatedProject> getAssociatedProjects(Long projectId) {
 	 * @param projectId           identifier for the current project
 	 * @param associatedProjectId identifier for the project to associate
 	 * @param locale              currently logged in users locale
-	 * @throws Exception if the project or associated project cannot be found
+	 * @throws UIAddAssociatedProjectException if the project or associated project cannot be found
 	 */
-	public void addAssociatedProject(long projectId, long associatedProjectId, Locale locale) throws Exception {
+	public void addAssociatedProject(long projectId, long associatedProjectId, Locale locale)
```
[the remark this answers is not in the document]
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIAssociatedProjectsService.java:103]: Sample question, why?

File: src/main/resources/i18n/messages.properties (hunk 4 above)
Comment (joshsadam) [reply src/main/resources/i18n/messages.properties]: Updated in 841f01b

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectAssociatedProjectsAjaxController.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectAssociatedProjectsAjaxController.java]: Updated in 1d9da2a

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIAssociatedProjectsService.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIAssociatedProjectsService.java]: Updated in cfe399b

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectSampleService.java [hunk 12]
```diff
@@ -52,8 +54,6 @@ public UIProjectSampleService(ProjectService projectService, SampleService sampl
 	public ResponseEntity<SampleNameValidationResponse> validateNewSampleName(String name, long projectId, Locale locale) {
```
[the remark this answers is not in the document]
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectSampleService.java:54]: Updated in cc51445fbf9dfaeb29e28d1526fdf76094071749

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java [hunk 13]
```diff
@@ -248,4 +285,429 @@ public void shareSamplesWithProject(ShareSamplesRequest request, Locale locale)
...
+
+	/**
+	 * Get the sequence files for a list of samples
+	 *
+	 * @param projectId Identifier for the project
+	 * @param sampleIds List of identifiers for samples
+	 * @param response  {@link HttpServletResponse}
+	 * @return Zip File containing sequence files for listed samples
+	 */
+	public StreamingResponseBody downloadSamples(long projectId, List<Long> sampleIds, HttpServletResponse response) {
```
[the remark this answers is not in the document]
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java]: Updated in 0e5c92d

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java [hunk 14]
```diff
@@ -248,4 +285,429 @@ public void shareSamplesWithProject(ShareSamplesRequest request, Locale locale)
...
+	 *
+	 * @param projectId Identifier for the project
+	 * @param type      The type of file to generate (either excel or csv)
+	 * @param request   The project samples table request
+	 * @param response  The response
+	 * @param locale    The current locale
+	 * @throws IOException If there is an error writing the file
+	 */
+	@Transactional(readOnly = true)
+	public void downloadSamplesSpreadsheet(long projectId, String type, ProjectSamplesTableRequest request,
```
[the remark this answers is not in the document]
Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java]: Updated in 0e5c92d

File: .gitignore (hunk 5 above)
[the remark this answers is not in the document]
Comment (ericenns) [reply .gitignore:34]: According to yarn those files are ok to be commited. Please look at this page for what should be in the .gitignore https://yarnpkg.com/getting-started/qa/#which-files-should-be-gitignored

File: src/main/webapp/resources/js/pages/projects/samples/components/CreateNewSample.jsx [hunk 15]
```diff
@@ -0,0 +1,120 @@
...
+import { AutoComplete, Form, Input, Modal } from "antd";
+import {
+  createNewSample,
+  validateSampleName,
+} from "../../../../apis/projects/samples";
+import searchOntology from "../../../../apis/ontology/taxonomy/query";
+
+/**
+ * React component to create a new sample within a project.
+ * @returns {JSX.Element}
```
Comment (deepsidhu85) [inline src/main/webapp/resources/js/pages/projects/samples/components/CreateNewSample.jsx:11]: Add params/functions in the jsdoc

File: src/main/webapp/resources/js/pages/projects/samples/components/FilterByFileModal.jsx [hunk 16]
```diff
@@ -0,0 +1,144 @@
...
+import { useSelector } from "react-redux";
+import { CheckCircleTwoTone, WarningTwoTone } from "@ant-design/icons";
+import { green6, red6 } from "../../../../styles/colors";
+import VirtualList from "rc-virtual-list";
+import { SPACE_SM } from "../../../../styles/spacing";
+
+const ROW_HEIGHT = 43;
+
+/**
+ * React component to render a modal to allow the user to select a file containing coma or new
```
Comment (deepsidhu85) [inline src/main/webapp/resources/js/pages/projects/samples/components/FilterByFileModal.jsx:12]: Typo in `coma` and `sample name` should be `sample names`

File: src/main/webapp/resources/js/pages/projects/samples/components/LinkerModal.jsx [hunk 17]
```diff
@@ -0,0 +1,104 @@
...
+        <div style={{ display: "flex", flexDirection: "row-reverse" }}>
+          <Button type="primary" onClick={onFinish}>
+            {i18n("Linker.close")}
+          </Button>
+        </div>
+      }
+    >
+      <Typography.Paragraph>{i18n("Linker.details")}</Typography.Paragraph>
+      <Typography.Text type="secondary">
+        <span dangerouslySetInnerHTML={{ __html: i18n("Linker.note") }} />
```
Comment (deepsidhu85) [inline src/main/webapp/resources/js/pages/projects/samples/components/LinkerModal.jsx:71]: Why do we need to use `dangerouslySetInnerHTML` here? Looking at `Linker.note` in the messages.properties file shows that there is no html in it

File: src/main/webapp/resources/js/pages/projects/samples/components/LinkerModal.jsx [hunk 18]
```diff
@@ -0,0 +1,104 @@
...
+        </Form.Item>
+        <Form.Item hidden name="command" value={command}>
+          <Input className="t-linker-cmd" />
+        </Form.Item>
+      </Form>
+      <CommandWrapper>
+        {scriptString === undefined ? (
+          <Space>
+            <LoadingOutlined />
+            <span>LOADING...</span>
```
Comment (deepsidhu85) [inline src/main/webapp/resources/js/pages/projects/samples/components/LinkerModal.jsx:90]: Internationalize `LOADING...`. Also, could it be the case because of an error on the server side that the linker modal just keeps displaying the loading message? We should probably catch any possible errors and set the text accordingly

File: src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx [hunk 19]
```diff
@@ -0,0 +1,182 @@
...
+ * @param {array} samples - list of samples to merge together
+ * @param {boolean} visible - whether the modal is currently visible on the page
+ * @param {function} onComplete - function to call when the merge is complete
+ * @param {function} onCancel - function to call when the merge is cancelled.
+ * @returns {JSX.Element}
+ * @constructor
+ */
+export default function MergeModal({ samples, visible, onComplete, onCancel }) {
+  const { projectId } = useSelector((state) => state.samples);
+  const [merge, { isLoading }] = useMergeMutation();
```
Comment (deepsidhu85) [inline src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx:30]: I don't think I've seen this before. Where is it getting the `isLoading` from? We usually get it from the state

File: src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx [hunk 20]
```diff
@@ -0,0 +1,182 @@
...
+    }
+  };
+
+  const onSubmit = async () => {
+    let values;
+
+    try {
+      values = await form.validateFields();
+    } catch {
+      return;
```
Comment (deepsidhu85) [inline src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx:64]: Can you just add a comment of where this returns to and what happens

File: src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx [hunk 21]
```diff
@@ -0,0 +1,182 @@
...
+
+    notification.success({
+      message: i18n("MergeModal.success"),
+      description: message,
+    });
+    onComplete();
+  };
+
+  // TODO: Handle rendering many samples?
+  // TODO: Handle rendering many locked samples?k
```
Comment (deepsidhu85) [inline src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx:86]: Remove k at the end of the line

File: src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx [hunk 22]
```diff
@@ -0,0 +1,182 @@
...
+                    </Space>
+                  </Radio.Group>
+                </Form.Item>
+                <Form.Item noStyle>
+                  <Checkbox
+                    className="t-custom-checkbox"
+                    checked={renameSample}
+                    onChange={(e) => setRenameSample(e.target.checked)}
+                  >
+                    Rename Sample
```
Comment (deepsidhu85) [inline src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx:147]: Internationalize

File: src/main/webapp/resources/js/pages/projects/samples/components/RemoveModal.jsx [hunk 23]
```diff
@@ -0,0 +1,85 @@
...
+  const [removeSamples, { isLoading }] = useRemoveMutation();
+
+  const onOk = async () => {
+    try {
+      const response = await removeSamples(
+        samples.valid.map((sample) => sample.id)
+      );
+      onComplete();
+    } catch (e) {
+      console.log(e);
```
Comment (deepsidhu85) [inline src/main/webapp/resources/js/pages/projects/samples/components/RemoveModal.jsx:34]: Add error notification and remove logging statement

File: src/main/webapp/resources/js/pages/projects/samples/components/RemoveModal.jsx [hunk 24]
```diff
@@ -0,0 +1,85 @@
...
+        loading: isLoading,
+      }}
+      width={600}
+    >
+      <Row gutter={[16, 16]}>
+        <Col span={24}>
+          <List
+            size="small"
+            bordered
+            header={<Typography.Text>Samples to be removed</Typography.Text>}
```
Comment (deepsidhu85) [inline src/main/webapp/resources/js/pages/projects/samples/components/RemoveModal.jsx:56]: Internationalize

File: src/main/webapp/resources/js/pages/projects/samples/components/SampleIcons.jsx [hunk 25]
```diff
@@ -0,0 +1,20 @@
+import React from "react";
+import { LockTwoTone } from "@ant-design/icons";
+import { Popover, Space } from "antd";
+import { red6 } from "../../../../styles/colors";
+
```
Comment (deepsidhu85) [inline src/main/webapp/resources/js/pages/projects/samples/components/SampleIcons.jsx:5]: Add file comment

File: src/main/webapp/resources/js/pages/projects/samples/components/SamplesMenu.jsx [hunk 26]
```diff
@@ -0,0 +1,361 @@
...
+
+  /**
+   * When a merge is completed, hide the modal and ask
+   * the table to reset
+   */
+  const onMergeComplete = () => {
+    setMergeVisible(false);
+    dispatch(reloadTable());
+  };
+
```
Comment (deepsidhu85) [inline src/main/webapp/resources/js/pages/projects/samples/components/SamplesMenu.jsx:75]: Can you add comments for each of these constants

File: src/main/webapp/resources/js/pages/projects/samples/index.js [hunk 27]
```diff
@@ -0,0 +1,33 @@
...
+import { render } from "react-dom";
+import ProjectSamples from "./components/ProjectSamples";
+import { configureStore } from "@reduxjs/toolkit";
+import { setupListeners } from "@reduxjs/toolkit/query";
+import { Provider } from "react-redux";
+import { samplesApi } from "../../../apis/projects/samples";
+import { associatedProjectsApi } from "../../../apis/projects/associated-projects";
+import samplesReducer from "../redux/samplesSlice";
+import { projectApi } from "../../../apis/projects/project";
+
```
Comment (deepsidhu85) [inline src/main/webapp/resources/js/pages/projects/samples/index.js:11]: File comment

File: src/main/webapp/resources/js/pages/projects/samples/services/constants.js [hunk 28]
```diff
@@ -0,0 +1,13 @@
+/**
+ * Initial state of the sample table
+ * @type {string}
+ */
+export const INITIAL_TABLE_STATE = JSON.stringify({
+  filters: { associated: null },
+  pagination: {
```
Comment (deepsidhu85) [inline src/main/webapp/resources/js/pages/projects/samples/services/constants.js:7]: Need to update the project samples table pagination to use the default pagination we had set up to keep the tables consistent. `getPaginationOptions` in `antdesign-table-utilities.js`

File: src/main/webapp/resources/js/pages/projects/samples/services/sample.utilities.js [hunk 29]
```diff
@@ -0,0 +1,51 @@
+/**
+ * Determine valid and invalid samples for merging samples.
+ *
+ */
+export function validateSamplesForMerge(samples) {
```
Comment (deepsidhu85) [inline src/main/webapp/resources/js/pages/projects/samples/services/sample.utilities.js:5]: Comments

File: src/main/webapp/resources/js/styles/colors.js [hunk 30]
```diff
@@ -12,7 +12,7 @@ export const blue10 = "hsl(217,100%,20%)";
 export const blue9 = "hsl(215,100%,28%)";
 export const blue8 = "hsl(213,100%,35%)";
 export const blue7 = "hsl(211,92%,44%)";
-export const blue6 = "hsl(209,100%,55%)";
+export const blue6 = "hsl(209,100%,55%)"; // In css
```
Comment (deepsidhu85) [inline src/main/webapp/resources/js/styles/colors.js:15]: Exand on this comment or remove :)

**Review by deepsidhu85 — CHANGES_REQUESTED** [review]
Looking good. Just some changes below

File: .gitignore (hunk 5 above)
[the remark this answers is not in the document]
Comment (deepsidhu85) [reply .gitignore:34]: Thanks @ericenns

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/dto/samples/SampleIdsRequest.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (deepsidhu85) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/dto/samples/SampleIdsRequest.java]: Thanks :)

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectAssociatedProjectsAjaxController.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (deepsidhu85) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectAssociatedProjectsAjaxController.java]: As discussed, for consistency since we use Long everywhere

File: .gitignore (hunk 5 above)
[the remark this answers is not in the document]
Comment (ericenns) [reply .gitignore:34]: Yeah @joshsadam please remove lines 34 - 37 and 39-40

[the remark this answers is not in the document]
Comment (joshsadam) [reply .gitignore:34]: Thanks @ericenns updated in 5dcedcf8ea3b8c2290703bf9487e3d77823438d2

File: src/main/webapp/resources/js/apis/projects/samples.js [hunk 31]
```diff
@@ -1,36 +1,58 @@
...
+      query: body => ({
+        url: `/share`,
         method: `POST`,
-        body,
-      }),
+        body
+      })
     }),
-  }),
+    //TODO: This should not be in the slice but async thunk (update in metadata security)
```
[the remark this answers is not in the document]
Comment (joshsadam) [reply src/main/webapp/resources/js/apis/projects/samples.js:41]: Not yet, it's working there so let's not move it quite yet.  Trying to decide if we should have 1 slice file for each type of IRIDA thing, by that I mean only one `samplesSlice` or `projectSlice`

File: src/main/webapp/resources/js/components/sample-quality/index.js [hunk 32]
```diff
@@ -0,0 +1,53 @@
...
+
+/**
+ * React component to render the quality data for a sample.
+ *
+ * @param {array} qualities - list of qc issues associated with the sample
+ * @returns {JSX.Element}
+ * @constructor
+ */
+export default function SampleQuality({ qualities }) {
+  if (qualities.length === 0) {
```
[the remark this answers is not in the document]
Comment (joshsadam) [reply src/main/webapp/resources/js/components/sample-quality/index.js:15]: Updated in 453d9998389f0b48fca153e48343fcf286826a9c

File: src/main/webapp/resources/js/pages/projects/redux/userSlice.js [hunk 33]
```diff
@@ -11,8 +11,8 @@ import { fetchCurrentUserDetails } from "../../../apis/users/user";
  */
 export const getCurrentUserDetails = createAsyncThunk(
   `user/getCurrentUserDetails`,
-  async () => {
-    const details = await fetchCurrentUserDetails();
+  async (projectId) => {
+    const details = await fetchCurrentUserDetails({ projectId });
```
[the remark this answers is not in the document]
Comment (joshsadam) [reply src/main/webapp/resources/js/pages/projects/redux/userSlice.js:15]: Updated in 0cecbaa70bcbfc782df1aee5d7ca5b75f3c743f6

File: src/main/webapp/resources/js/pages/projects/samples/components/CreateNewSample.jsx (hunk 15 above)
Comment (joshsadam) [reply src/main/webapp/resources/js/pages/projects/samples/components/CreateNewSample.jsx:11]: Don't think that is really necessary as it is the default form API from Ant Design as I have already stated in the JSDoc.  Any need references should be looked at there.

File: src/main/webapp/resources/js/pages/projects/samples/components/FilterByFileModal.jsx (hunk 16 above)
Comment (joshsadam) [reply src/main/webapp/resources/js/pages/projects/samples/components/FilterByFileModal.jsx:12]: Updated in 1d244ed0c434997c30f03d3c564e941ee05872ed

File: src/main/webapp/resources/js/pages/projects/samples/components/LinkerModal.jsx (hunk 17 above)
Comment (joshsadam) [reply src/main/webapp/resources/js/pages/projects/samples/components/LinkerModal.jsx:71]: Because I am asking React to set foreign HTML, not just a string.  It has to handle the parsing of that string to HTML and therefore needs to run it through a sanitizer.

File: src/main/webapp/resources/js/pages/projects/samples/components/LinkerModal.jsx (hunk 18 above)
Comment (joshsadam) [reply src/main/webapp/resources/js/pages/projects/samples/components/LinkerModal.jsx:90]: Updated i18n in 619c1b752b096298453a18d67ddc3d32ef3fa64c

Comment (joshsadam) [reply src/main/webapp/resources/js/pages/projects/samples/components/LinkerModal.jsx]: Added error in dfb593e

File: src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx (hunk 19 above)
Comment (joshsadam) [reply src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx:30]: https://redux-toolkit.js.org/rtk-query/usage/mutations#frequently-used-mutation-hook-return-values

File: src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx (hunk 20 above)
Comment (joshsadam) [reply src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx:64]: Added in 2c51dd84e378516b1bd4a5f39cf4ed5b14c70e85

File: src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx (hunk 21 above)
Comment (joshsadam) [reply src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx:86]: Removed the comments altogether.  Too many samples would be ridiculous to start with (although I guess if we get an issue we can update it later, but who would merge tons of samples together). Locked samples have been handled on line 177.

File: src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx (hunk 22 above)
Comment (joshsadam) [reply src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx:147]: Updated in f183bbc1d3423715d5e1df07b89a9d8b5c0da8f7

File: src/main/webapp/resources/js/pages/projects/samples/components/RemoveModal.jsx (hunk 23 above)
Comment (joshsadam) [reply src/main/webapp/resources/js/pages/projects/samples/components/RemoveModal.jsx]: Updated in 06ea327

File: src/main/webapp/resources/js/pages/projects/samples/components/RemoveModal.jsx (hunk 24 above)
Comment (joshsadam) [reply src/main/webapp/resources/js/pages/projects/samples/components/RemoveModal.jsx:54]: Updated in 0ca6f86ce463ac3d058e5a0f04aba2236bf797fb

File: src/main/webapp/resources/js/pages/projects/samples/components/SamplesMenu.jsx (hunk 26 above)
Comment (joshsadam) [reply src/main/webapp/resources/js/pages/projects/samples/components/SamplesMenu.jsx:99]: Updated in c09c8da

File: src/main/webapp/resources/js/pages/projects/samples/index.js (hunk 27 above)
Comment (joshsadam) [reply src/main/webapp/resources/js/pages/projects/samples/index.js:16]: Updated in 1443c41

File: src/main/webapp/resources/js/pages/projects/samples/services/constants.js (hunk 28 above)
Comment (joshsadam) [reply src/main/webapp/resources/js/pages/projects/samples/services/constants.js:7]: This will actually break my table.  It will cause unnecessary table reloads.  The reason for this is that changing any of the pagination options triggers a table reload, therefor if you filter and there is a new total it will reload the table a second time thinking that the user updated something in the pagination and it needs to get new data.

File: src/main/webapp/resources/js/pages/projects/samples/services/sample.utilities.js (hunk 29 above)
Comment (joshsadam) [reply src/main/webapp/resources/js/pages/projects/samples/services/sample.utilities.js:6]: Updated in 031c1a8

File: src/main/webapp/resources/js/styles/colors.js (hunk 30 above)
Comment (deepsidhu85) [reply src/main/webapp/resources/js/styles/colors.js]: Oh ok. Sounds good. Thanks

File: src/main/webapp/resources/js/pages/projects/samples/components/RemoveModal.jsx (hunk 24 above)
Comment (deepsidhu85) [reply src/main/webapp/resources/js/pages/projects/samples/components/RemoveModal.jsx]: Sorry to be a pain but can you change the translation key (`RemoveModal.good`) so it's clear what it is?

File: src/main/webapp/resources/js/apis/projects/samples.js (hunk 31 above)
[the remark this answers is not in the document]
Comment (deepsidhu85) [reply src/main/webapp/resources/js/apis/projects/samples.js:41]: Sounds good

File: src/main/webapp/resources/js/pages/projects/samples/components/FilterByFileModal.jsx (hunk 16 above)
Comment (deepsidhu85) [reply src/main/webapp/resources/js/pages/projects/samples/components/FilterByFileModal.jsx]: I think an accidentally `'` was added to the end of `the samples'`

File: src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx (hunk 21 above)
Comment (deepsidhu85) [reply src/main/webapp/resources/js/pages/projects/samples/components/MergeModal.jsx]: Yeah true enough. Thanks

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (deepsidhu85) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java]: Missing the beginning opening curly brace before `@link`

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIAssociatedProjectsService.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (deepsidhu85) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIAssociatedProjectsService.java]: As discussed, for consistency since we always use `Long`

File: src/main/webapp/resources/js/pages/projects/samples/components/FilterByFileModal.jsx (hunk 16 above)
Comment (joshsadam) [reply src/main/webapp/resources/js/pages/projects/samples/components/FilterByFileModal.jsx]: Nope, that's actually proper grammar I believe

Comment (deepsidhu85) [reply src/main/webapp/resources/js/pages/projects/samples/components/FilterByFileModal.jsx]: I don't believe it is :)

Comment (deepsidhu85) [reply src/main/webapp/resources/js/pages/projects/samples/components/FilterByFileModal.jsx]: Guess you were right! :)

File: src/main/webapp/resources/js/pages/projects/samples/components/LinkerModal.jsx (hunk 17 above)
Comment (deepsidhu85) [reply src/main/webapp/resources/js/pages/projects/samples/components/LinkerModal.jsx:83]: Whoops looks like I looked at the wrong line in the messages file. My bad :)

File: src/main/webapp/resources/js/pages/projects/samples/services/constants.js (hunk 28 above)
Comment (ericenns) [reply src/main/webapp/resources/js/pages/projects/samples/services/constants.js:7]: @deepsidhu85 me and @joshsadam did some testing and are able to use the call without any extra renders. He also updated all calls to `getPaginationOptions` to be done on table component initialization instead of using `useMemo` since this function is not computationally intensive so no benefit to using `useMemo`.

Comment (deepsidhu85) [reply src/main/webapp/resources/js/pages/projects/samples/services/constants.js:7]: Awesome thanks @ericenns

File: doc/user/user/samples/index.md [hunk 34]
```diff
@@ -126,100 +126,75 @@ Adding a new sample
...
-
-![Filter by File Button](images/filter_by_file_btn.png)
+![Filter by file preview.](images/filter-by-file.gif)
 
-* Select the file you created.  The samples will be filtered by these names.
+![Filter by File button](images/filter-by-file-button.png)
 
-If all sample names are found, a green success notification will appear in the upper right corner of the window.  This notification will disappear after 2 seconds.
+To filter the table by file click the "Filter by File" button at the top of the table. This will open a modal window
+which will allow you to select the file containing the list of names to filter by. Once selected, IRIDA will if the
```
Comment (deepsidhu85) [inline doc/user/user/samples/index.md:187]: Should this read `IRIDA will display`

**Review by deepsidhu85 — CHANGES_REQUESTED** [review]
One final thing before I do a final review

File: doc/user/user/samples/index.md (hunk 34 above)
Comment (joshsadam) [reply doc/user/user/samples/index.md]: Updated in d9a816b58e492403ff3fcf76fd26caff5b893e2f

**Review by deepsidhu85 — APPROVED** [review]
Amazing work!
