### PR TITLE
Changed trim for tablerequests

### LINKED ISSUE #605: ClientsControllerTest failing after hotfix
## Describe the bug
`ClientsControllerTest.testGetAjaxClientList` is failing due to the hotfix lower casing the search terms coming in to the new ant tables.

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. ran `mvn test`
2. `ClientsControllerTest.testGetAjaxClientList` failed
3. 

## Expected behaviour
`ClientsControllerTest.testGetAjaxClientList` pass

## Additional context
It's a null pointer due to the change to ant design on the clients table.  It looks like no search term is being sent to the tablerequest.

### PR DESCRIPTION
**Pull request by tom114**
## Description of changes
Changed the search term to be trimmed when it's set for the `TableRequest` instead of when it's requested.  The issue was that if there's no search term and the getter is called, it's trying to trim it then which would throw a nullpointer.

## Related issue
Fixes #605 

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

~* [] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~ Not bothering because we caused this error with the hotfix.  Not really a change.
~* [ ] Tests added (or description of how to test) for any new features.~
~* [ ] User documentation updated for UI or technical changes.~

### CODE REVIEW

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/tables/TableRequest.java [hunk 1]
```diff
@@ -40,11 +40,11 @@ public void setSortColumn(String sortColumn) {
 	}
 
 	public String getSearch() {
-		return search.trim();
+		return search;
 	}
 
 	public void setSearch(String search) {
-		this.search = search;
+		this.search = search.trim();
```
Comment (joshsadam) [inline src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/tables/TableRequest.java]: Wouldn't this still through an error if the search argument is `null`?

Comment (tom114) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/tables/TableRequest.java]: I don't think it should happen that a null ever gets set here, but I did it just in case in 90b5c05.

Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/tables/TableRequest.java]: Thanks, that looks good.  Agreed thought that it shouldn't but safe is good.
