### PR TITLE
Import columns with numerical headers

### LINKED ISSUE #340: IRIDA cannot import metadata where column names are numerical
## Describe the bug

If there are any column names in a spreadsheet that are numerical, IRIDA cannot import the data into the metadata system.

## Steps to reproduce the problem
1. Create a spreadsheet with numerical column names.
    
    image

2. Try to import the spreadsheet in IRIDA.
3. The following exception will be produced.

image

```
05 Apr 2019 15:01:44,436 ERROR ca.corefacility.bioinformatics.irida.ria.web.errors.ExceptionHandlerController:117 - Cannot get a STRING value from a NUMERIC cell
java.lang.IllegalStateException: Cannot get a STRING value from a NUMERIC cell                                  
        at org.apache.poi.xssf.usermodel.XSSFCell.typeMismatch(XSSFCell.java:1077)                                 
        at org.apache.poi.xssf.usermodel.XSSFCell.getRichStringCellValue(XSSFCell.java:395)                                                              
        at org.apache.poi.xssf.usermodel.XSSFCell.getStringCellValue(XSSFCell.java:347)                            
        at ca.corefacility.bioinformatics.irida.ria.web.projects.metadata.ProjectSampleMetadataController.getWorkbookHeaders(ProjectSampleMetadataController.java:177)
        at ca.corefacility.bioinformatics.irida.ria.web.projects.metadata.ProjectSampleMetadataController.createProjectSampleMetadata(ProjectSampleMetadataController.java:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
```

## Expected behaviour
I expected to be able to import the data.

## Additional context

Test spreadsheet 
[test.xlsx](https://github.com/phac-nml/irida/files/3049431/test.xlsx)

### PR DESCRIPTION
**Pull request by joshsadam**
## Description of changes
Fixes bug that occured when users try to import an excel spreadsheet with numerical values.

## Related issue
Fixes #340 

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [X] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
~~* [ ] Tests added (or description of how to test) for any new features.~~
~~* [ ] User documentation updated for UI or technical changes.~~

### CODE REVIEW

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/metadata/ProjectSampleMetadataController.java [hunk 1]
```diff
@@ -165,8 +165,16 @@ public SampleMetadataStorage createProjectSampleMetadata(HttpSession session, @P
...
-			String headerValue = headerCell.getStringCellValue()
-					.trim();
+			CellType cellType = headerCell.getCellTypeEnum();
+
+			String headerValue;
+			if (cellType.equals(CellType.STRING)) {
+				headerValue = headerCell.getStringCellValue()
+						.trim();
+			} else {
+				headerValue = String.valueOf(headerCell.getNumericCellValue())
```
Comment (apetkau) [inline src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/metadata/ProjectSampleMetadataController.java]: If I upload a spreadsheet with a column header of `1`, this will end up setting the headerValue to `1.0`.

Is there another method in here to get the cell contents as a string even if it is numeric?

Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/metadata/ProjectSampleMetadataController.java]: The java excel parser assumes that any cell that has a number in it, must be a number cell.  Very frustrating.  Sorry I have not found a way around this, so that `*.0` will always be there since we have no way of knowing if that is what the user intended or not.

Comment (apetkau) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/metadata/ProjectSampleMetadataController.java]: Okay. I think this is acceptable (and preferable to not being able to load the spreadsheet at all).

**Comment by apetkau** [comment]
Could you merge `development` into here to resolve merge conflicts?

**Comment by joshsadam** [comment]
Dev merge up, thanks

**Comment by apetkau** [comment]
Thanks Josh. This looks great.
