### PR TITLE
Syncing with older versions of IRIDA

### LINKED ISSUE #819: Cannot sync with older IRIDA instances
## Describe the bug
When attempting to sync with older IRIDA instances I get the following error:

```
05 Oct. 2020 17:55:10,358 DEBUG ca.corefacility.bioinformatics.irida.service.remote.ProjectSynchronizationService:162 - An err
or occurred while synchronizing project http://localhost/irida/api/projects/7
java.lang.NullPointerException
        at ca.corefacility.bioinformatics.irida.service.remote.impl.GenomeAssemblyRemoteServiceImpl.getGenomeAssembliesForSamp
le(GenomeAssemblyRemoteServiceImpl.java:47)
        at ca.corefacility.bioinformatics.irida.service.remote.ProjectSynchronizationService.syncSample(ProjectSynchronization
Service.java:375)
        at ca.corefacility.bioinformatics.irida.service.remote.ProjectSynchronizationService.syncProject(ProjectSynchronizatio
nService.java:254)
        at ca.corefacility.bioinformatics.irida.service.remote.ProjectSynchronizationService.findMarkedProjectsToSync(ProjectS
ynchronizationService.java:152)
        at ca.corefacility.bioinformatics.irida.config.services.scheduled.ProjectSyncScheduledTaskConfig.syncProject(ProjectSy
ncScheduledTaskConfig.java:27)
...
```

## Steps to reproduce the problem
1. Setup an older IRIDA instance and newer one (20.09.1).
2. Setup client in older IRIDA, connect via the 20.09.1 version of IRIDA.
3. Attempt to sync a project in the newer IRIDA (20.09.1).

## Expected behaviour
I expected to be able to synchronize projects from older IRIDA instances.

## Additional context
None.

### PR DESCRIPTION
**Pull request by tom114**
## Description of changes
Allowing IRIDA 20.09 to synchronize with older versions which do not yet have the assemblies available in the REST API.

## Related issue
Fixes #819 

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [x] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [x] Tests added (or description of how to test) for any new features.
~* [ ] User documentation updated for UI or technical changes.~

### CODE REVIEW

File: src/main/java/ca/corefacility/bioinformatics/irida/service/remote/ProjectSynchronizationService.java [hunk 1]
```diff
@@ -371,8 +374,16 @@ private void syncProject(Project project) {
...
 
-		//list the remote assemblies for the sample
-		List<UploadedAssembly> genomeAssembliesForSample = assemblyRemoteService.getGenomeAssembliesForSample(sample);
+		//list the remote assemblies for the sample.
+		List<UploadedAssembly> genomeAssembliesForSample;
+		try {
+			genomeAssembliesForSample = assemblyRemoteService.getGenomeAssembliesForSample(sample);
+		} catch (LinkNotFoundException e) {
+			//if the target IRIDA doesn't support assemblies yet, warn and ignore assemblies.
+			logger.warn("The referenced IRIDA instance doesn't support assemblies.");
```
Comment (apetkau) [inline src/main/java/ca/corefacility/bioinformatics/irida/service/remote/ProjectSynchronizationService.java:383]: Would it be possible to print the URL to the referenced IRIDA instance?

Comment (tom114) [reply src/main/java/ca/corefacility/bioinformatics/irida/service/remote/ProjectSynchronizationService.java]: Sure.  Added in ce0cf1f

**Review by apetkau — APPROVED** [review]
This looks good. I tested it out. It works.
