### PR TITLE
Remove gravatar

### LINKED ISSUE #596: Gravatar image requested using http
## Describe the bug
Briefly describe the issue you encountered.

The browser https URL bar lock icon shows a cautionary notice indicating that some parts of the page are fetched using an insecure connection. 

## Steps to reproduce the problem
What were you doing when you encountered the problem?

1. Login to IRIDA through a https connection
2. Observe the lock icon in the browser URL bar

## Expected behaviour
What did you expect to happen?

The lock icon should indicate a secure connection.

## Additional context
Additional information to help solve the problem.  Test files, screenshots, IRIDA version information can go here.

Screenshot from 2020-02-11 12-23-46

Gravatar URL is set in a template here:
https://github.com/phac-nml/irida/blob/ea77d2d765123cdb9a3b64eb6bee6b104d61f1ec/src/main/webapp/pages/template/main-navigation.html#L219

### PR DESCRIPTION
**Pull request by joshsadam**
## Description of changes
Completely removed using gravatar and replaced with a simple icon.

## Related issue
Fixes #596 

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [X] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
~~* [ ] Tests added (or description of how to test) for any new features.~~
~~* [ ] User documentation updated for UI or technical changes.~~

### CODE REVIEW

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/security/LoginSuccessHandler.java [hunk 1]
```diff
@@ -1,35 +1,32 @@
...
 public class LoginSuccessHandler extends SavedRequestAwareAuthenticationSuccessHandler {
 	private static final Logger logger = LoggerFactory.getLogger(LoginSuccessHandler.class);
 
-	private static final String GRAVATAR_ATTRIBUTE = "gravatar";
-
-	private UserRepository userRepository;
+	private final UserRepository userRepository;
 
-	private LocaleResolver localeResolver;
+	private final LocaleResolver localeResolver;
```
Comment (tom114) [inline src/main/java/ca/corefacility/bioinformatics/irida/ria/security/LoginSuccessHandler.java:29]: Its ok that these are getting set as `final`, but I think your formatter is running amok again.

File: CHANGELOG.md [hunk 2]
```diff
@@ -13,6 +14,7 @@ Changes
 * [UI]: Fixed bug when creating/modifying a metadata template the user could not search for a field. (20.05.1)
 * [UI]: Fixed bug where managers could not load Users listing page. (20.05.1)
 * [UI]: Added functionality for users to synchronize assembly data from remote APIs.
+* [UI]: Removed gravatar and replaced with user icon.
```
Comment (tom114) [inline CHANGELOG.md:17]: Wasn't the plan to use this library as a replacement? https://ant.design/components/avatar/

File: doc/user/user/dashboard/index.md [hunk 3]
```diff
@@ -124,7 +124,7 @@ You will be shown a confirmation and your browser will reload the current page.
 User Settings
 -------------
 
-The settings menu allows you to view and edit the details of your own user account. This menu also allows you to update your email subscription preferences.  You can find the settings menu in the top, right-hand corner of the page, if you have a [Gravatar](https://en.gravatar.com/) account associated with your email in IRIDA, your gravatar will be displayed:
+The settings menu allows you to view and edit the details of your own user account. This menu also allows you to update your email subscription preferences.  You can find the settings menu in the top, right-hand corner of the page under the user icon:
```
Comment (tom114) [inline doc/user/user/dashboard/index.md:127]: If the style is changing this drastically, pictures in the docs that focus on the user icon should be redone.  At first look I can find this one: https://irida.corefacility.ca/documentation/user/user/dashboard/#user-settings

File: CHANGELOG.md (hunk 2 above)
Comment (joshsadam) [reply CHANGELOG.md:17]: It will be eventually, I just wanted to get gravatar out in a simple merge request.  I have another branch I am working on that is a full menu bar re-write, but it won't be ready for a little bit.  This is a baby step.  The full replacement bar should be done by the next release, but that will be big enough.

File: doc/user/user/dashboard/index.md (hunk 3 above)
Comment (joshsadam) [reply doc/user/user/dashboard/index.md:127]: Isn't the one you referenced this one that I already replaced?  As I stated in my previous reply, this is just a baby step to replacing the full menu bar, so all the images will have to be replaced at that time.

File: src/main/webapp/pages/template/main-navigation.html [hunk 4]
```diff
@@ -212,15 +212,15 @@
                         </ul>
                     </li>
                     <li class="dropdown">
-                        <a href="#" class="dropdown-toggle nav-gravatar-wrapper" data-toggle="dropdown" role="button" aria-haspopup="true"
+                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                            aria-expanded="false">
-                            <img class="nav-gravatar" th:src="${session.gravatar}" alt="User Icon"/>
+                            <i class="far fa-user nav-icon"></i>
```
Comment (tom114) [inline src/main/webapp/pages/template/main-navigation.html:217]: Thoughts on using a circle style icon instead so the style stays a bit more familiar until we get the new topbar done?  If we used something like this we can get by without a whole bunch of docs changes.  https://fontawesome.com/icons/user-circle?style=solid

File: doc/user/user/dashboard/index.md (hunk 3 above)
Comment (tom114) [reply doc/user/user/dashboard/index.md:127]: The only one I would definitely like changed is the image immediately below this comment.  Its directly focusing on the icon which now looks different.  Whatever icon we choose should be in this screenshot please.

File: src/main/webapp/pages/template/main-navigation.html (hunk 4 above)
Comment (joshsadam) [reply src/main/webapp/pages/template/main-navigation.html:217]: Updated icon in 70f5272a1e2d1e50b3594b0ed453dd24905b7c4d

File: doc/user/user/dashboard/index.md (hunk 3 above)
Comment (joshsadam) [reply doc/user/user/dashboard/index.md:127]: I think the correct image has been updated with the solid icon.

**Comment by tom114** [comment]
Looks good after the changes.  Thanks for the change.  Merging.
