### PR TITLE
Hotfix: managers cannot see users

### LINKED ISSUE #732: Exception thrown when viewing users list as a manager
## Describe the bug
Briefly describe the issue you encountered.

When attempting to view the Users list as a Manager the page throws an error.

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Create an account with a role of Manager
2. Login as the manager
3. Click the gear cog and then the Users menu item
4. Page throws an HTTP ERROR 500 javax.servlet.ServletException

## Expected behaviour
What did you expect to happen?

I expected to be able to see a list of users

## Additional context
Additional information to help solve the problem.  Test files, screenshots, IRIDA version information can go here.

### PR DESCRIPTION
**Pull request by joshsadam**
## Description of changes
Fixed issue where managers could not load the Users page.  This was a mistake I made.  I had to update the UI components to ensure that a manager could not modify the user.

## Related issue
Fixes #732 

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [X] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [X] Tests added (or description of how to test) for any new features.
* [ ] ~~User documentation updated for UI or technical changes.~~

### CODE REVIEW

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/users/UsersController.java [hunk 1]
```diff
@@ -91,7 +91,7 @@ public UsersController(UserService userService, ProjectService projectService,
 	 * @return The name of the page.
 	 */
 	@RequestMapping
-	@PreAuthorize("hasRole('ROLE_ADMIN')")
+	@PreAuthorize("hasAnyRole('ROLE_ADMIN', 'ROLE_MANAGER')")
```
Comment (tom114) [inline src/main/java/ca/corefacility/bioinformatics/irida/ria/web/users/UsersController.java:94]: Another change to add in this file please.  The original issue was that it was throwing a `500` when access was denied.  Can you remove the `handleAccessDenied` method at the bottom of this file?  That's what was causing the 500 error as the template it's trying to load doesn't exist.  If a user tries to access this page it'll give the access denied page as it should.

Comment (joshsadam) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/users/UsersController.java:92]: Removed in 1845c17

Comment (tom114) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/users/UsersController.java:92]: Thanks.  This looks good.  I'll merge and push the release.
