### PR TITLE
Fix user group removal from project

### LINKED ISSUE #115: Cannot delete Group when it's been added to a Project
If you attempt to delete a group after it's been added to a project (e.g., by clicking the trash icon below)

image

Then the following exception will be thrown

```
02 Nov 2017 11:06:49,157 ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper:146 - Cannot delete or update a parent row: a foreign key constraint fails (`irida_test`.`project_event`, CONSTRAINT `FK_USER_GROUP_PROJECT_EVENT` FOREIGN KEY (`user_group_id`) REFERENCES `user_g
roup` (`id`))
02 Nov 2017 11:06:49,182 ERROR ca.corefacility.bioinformatics.irida.ria.web.errors.ExceptionHandlerController:117 - could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statemen
t
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:259)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:225)
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:485)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:291)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodIntercceptor.invoke(CrudMethodMetadataPostProcessor.java:111)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
        at com.sun.proxy.$Proxy159.delete(Unknown Source)
        at ca.corefacility.bioinformatics.irida.service.impl.CRUDServiceImpl.delete(CRUDServiceImpl.java:99)
        at ca.corefacility.bioinformatics.irida.service.impl.user.UserGroupServiceImpl.delete(UserGroupServiceImpl.java:120)
        at ca.corefacility.bioinformatics.irida.service.impl.user.UserGroupServiceImpl.delete(UserGroupServiceImpl.java:49)
        at ca.corefacility.bioinformatics.irida.service.impl.user.UserGroupServiceImpl$$FastClassBySpringCGLIB$$e208ab7d.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:718)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:654)
        at ca.corefacility.bioinformatics.irida.service.impl.user.UserGroupServiceImpl$$EnhancerBySpringCGLIB$$5337e6b6.delete(<generated>)
        at ca.corefacility.bioinformatics.irida.ria.web.GroupsController.deleteGroup(GroupsController.java:217)
...
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`irida_test`.`project_event`, CONSTRAINT `FK_USER_GROUP_PROJECT_EVENT` FOREIGN KEY (`user_group_id`) REFERENCES `user_
group` (`id`))
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

Imported from GitLab issue #549.  Originally posted on 2017/11/02 01:38PM

### PR DESCRIPTION
**Pull request by deepsidhu85**
## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

Fixed removal of user groups that have been added to projects. Before this fix the user group could not be removed if it was linked to any projects

**To test these changes:**

First create a few groups and a few projects. Then add groups to these projects. Go to the groups page and click that trash can icon next to any of the groups that you have added to a project to delete this group. You should get a popup with a warning about the group being linked to a project or projects. Clicking the "Remove Group" button should delete the group.

Note: Try this out with a group linked to no projects and linked to 1,3, and 4 projects. You should receive the correct translations depending on the number of projects linked to the group.

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

Fixes #115

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [x] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [x] Tests added (or description of how to test) for any new features.
~~* [ ] User documentation updated for UI or technical changes.~~

### CODE REVIEW

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/GroupsController.java [hunk 1]
```diff
@@ -379,17 +380,24 @@ public DataTablesResponse getGroupUsers(@DataTablesRequest DataTablesParams para
...
+	 *
+	 * @param userGroupId the user group that's about to be deleted.
+	 * @param model       model for rendering view
 	 * @return a message indicating which group is going to be deleted.
 	 */
 	@RequestMapping(path = "/deleteConfirmModal", method = RequestMethod.POST)
 	public String getDeleteGroupText(final @RequestParam Long userGroupId, final Model model) {
 		final UserGroup group = userGroupService.read(userGroupId);
+		final Collection<UserGroupProjectJoin> projects = userGroupService.getProjectsWithUserGroup(group);
+		final int maxProjectsToDisplay = 3;
```
Comment (tom114) [inline src/main/java/ca/corefacility/bioinformatics/irida/ria/web/GroupsController.java]: Move this to top of the file as a global `public static final int` instead of a method scoped variable please.

Comment (deepsidhu85) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/GroupsController.java]: Fixed in 718fc62d032b6a56f4323020dcce64e973e34626

**Comment by deepsidhu85** [comment]
> All seems to work well, thanks. Move that one variable and I think it's good to go!

Awesome thanks! All done :)

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/GroupsController.java (hunk 1 above)
Comment (tom114) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/GroupsController.java]: Thanks for moving it. Can you change the var name to `CAPS_WITH_UNDERSCORES` so `MAX_PROJECTS_TO_DISPLAY`?  It's just a good naming convention for constant variables in Java.

**Comment by tom114** [comment]
Also there's a conflict now in CHANGELOG.md

File: src/main/java/ca/corefacility/bioinformatics/irida/ria/web/GroupsController.java (hunk 1 above)
Comment (deepsidhu85) [reply src/main/java/ca/corefacility/bioinformatics/irida/ria/web/GroupsController.java]: No problem. Done!  Fixed in 0502bcda79e734e6892aa9e2f7110bd7e8986625
