### PR TITLE
HOTFIX: Remote project manager members/groups permissions

### LINKED ISSUE #1043: Managers on synchronized projects cannot add new members to a project
## Describe the bug

If you are a **Manager** on a synchronized project (and not a system **Admin** user) then you cannot add new members to that project (that is, the **Add Project Member** button is missing).

image

However, for non-synchronized projects (i.e., normal projects) you can add new members (the **Add Project Member** button is present).

image

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Create a new synchronized project. Add a user `user` as a **Manager** of this project.
2. Login as `user` and go to **Settings > Members** in the project.
3. The **Add Project Member** button will be missing.

## Expected behaviour
I expected to be able to add project members as a **Manager** of a synchronized project.

## Additional context
None.

### PR DESCRIPTION
**Pull request by deepsidhu85**
## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

This hotfix fixes bug preventing a manager on a remote project from adding and removing members/groups.

**To test:**

1) Create a synchronized project
2) Add a user to the sync'd project and give them a `Manager` role
3) Login as the manager user from above
4) In the remote `Project -> Settings -> Members` you should be able to see the `Add Project Member` button and be able to add a user to the project.
5) In the remote `Project -> Settings -> Groups` you should be able to see the `Add User Group` button and be able to add a user group to the project.
6) You should also be able to remove the users and groups added above

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

Fixes #1043 

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [X] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [X] Tests added (or description of how to test) for any new features.
~* [] User documentation updated for UI or technical changes.~

### CODE REVIEW

File: src/main/webapp/resources/js/components/project-members/ProjectMembersTable.jsx [hunk 1]
```diff
@@ -69,7 +69,7 @@ export function ProjectMembersTable({ projectId }) {
     },
   ];
 
-  if (project.canManage) {
+  if (project.canManage || project.canManageRemote) {
```
Comment (tom114) [inline src/main/webapp/resources/js/components/project-members/ProjectMembersTable.jsx:72]: you can test this, but i'm pretty sure this can just be `canManageRemote`.  If `canManageRemote` is true, `canManage` will also be true.

File: src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMembersPageIT.java [hunk 2]
```diff
@@ -64,4 +69,58 @@ public void testCollaborator() {
 		ProjectMembersPage page = ProjectMembersPage.goTo(driver());
 		assertFalse("Add Members button should not be visible", page.isAddMemberBtnVisible());
 	}
+
+	@Test
+	public void testRemoteProjectManagerPageSetup() {
```
Comment (tom114) [inline src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMembersPageIT.java:74]: Thanks a bunch for adding the tests for this.

**Review by tom114 — CHANGES_REQUESTED** [review]
Thanks @deepsidhu85 , just one comment below that might simplify the conditionals.  Can you check it out?

File: src/main/webapp/resources/js/components/project-members/ProjectMembersTable.jsx (hunk 1 above)
Comment (deepsidhu85) [reply src/main/webapp/resources/js/components/project-members/ProjectMembersTable.jsx]: Yup that worked. Thanks. Updated in 7f7480049c4741f4b066167fbc1dbd994df5ccb8

File: src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMembersPageIT.java (hunk 2 above)
Comment (deepsidhu85) [reply src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMembersPageIT.java:74]: No problem. Thought it would be a good idea to have them :)

**Review by tom114 — APPROVED** [review]
