### PR TITLE
Concatenate zipped fastq

### LINKED ISSUE #481: Sequence concatenator doesn't work with compressed data
## Describe the bug
When concatenating a `.fastq.gz` sequence file from the UI, the result is a `.fastq` file that doesn't process correctly.

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. On sample/files page click concatenate.
2. Select `.fastq.gz` files to concatenate and click go.
3. Result is `.fastq` file that fails processing.

## Expected behaviour
Files to be correctly concatenated and valid `.fastq.gz` files.

## Additional context
File concatenator is assuming files are `.fastq` extensions and not correctly merging the zipped files.

### PR DESCRIPTION
**Pull request by tom114**
## Description of changes
Fixed the file concatenation methods to work with `.fastq.gz` data.  Previously the file extension was hardcoded as `.fastq` so the file processing would fail.  Also the method we were using to concatenate the files didn't work with gzipped data.

To test, upload multiple files to a sample, wait for them to file process, then concatenate from the sample/files page.  Then change the `file.processing.decompress=` value in your `/etc/irida/irida.conf` file and try the same again.

## Related issue
Fixes #481 

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [x] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [x] Tests added (or description of how to test) for any new features.
~* [ ] User documentation updated for UI or technical changes.~

### CODE REVIEW

File: src/main/java/ca/corefacility/bioinformatics/irida/processing/concatenate/SequencingObjectConcatenator.java [hunk 1]
```diff
@@ -1,63 +1,97 @@
...
+	 * @throws ConcatenateException if there is an error appending the file
 	 */
 	protected void appendToFile(Path target, SequenceFile file) throws ConcatenateException {
 
-		try (FileWriter fw = new FileWriter(target.toFile(), true);
-				BufferedWriter writer = new BufferedWriter(fw);
-				FileReader reader = new FileReader(file.getFile().toFile())) {
-
-			IOUtils.copy(reader, writer);
+		try (FileChannel out = FileChannel.open(target, StandardOpenOption.CREATE, StandardOpenOption.APPEND,
```
Comment (tom114) [inline src/main/java/ca/corefacility/bioinformatics/irida/processing/concatenate/SequencingObjectConcatenator.java]: Switched this to use `FileChannel` instead of the `FileWriter`.  `FileWriter` was having issues reading/writing the gzip files.  `FileChannel` is also a fair bit faster.

**Comment by tom114** [comment]
Re: The zipping after change in `file.processing.decompress`, I think that's more of an option in your initial setup.  Don't think we need to address that yet.
